---
- name: "Converge — AppArmor Ubuntu"
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Include linux_apparmor_ubuntu"
      ansible.builtin.include_role:
        name: "linux_apparmor_ubuntu"
