---
- name: "Apply login banners hardening (RHEL 9 family)"
  when: "linux_login_banner_disabled is not defined or not linux_login_banner_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_login_banner_rhel9"
