---
- name: "Apply IPv6 hardening (RHEL 9 family)"
  when: "linux_ipv6_disabled is not defined or not linux_ipv6_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_ipv6_rhel9"
