---
- name: "Converge — Authselect RHEL9"
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Include linux_authselect_rhel9"
      ansible.builtin.include_role:
        name: "linux_authselect_rhel9"
