---

linux_aide_enabled: true

# Paths to monitor (CIS recommended + critical infra additions)
linux_aide_monitored_paths:
  - "/bin"
  - "/sbin"
  - "/usr/bin"
  - "/usr/sbin"
  - "/etc"
  - "/boot"
  - "/var/log"
  - "/root"

# Cron schedule for daily checks (CIS Level 2)
linux_aide_cron_time: "0 5 * * *"

# Role disable var
linux_aide_disabled: false
