---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: rhel9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  inventory:
    host_vars:
      rhel9:
        ansible_become: false
        ansible_user: root

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint
