---
- name: "Apply SSH server hardening (Ubuntu/Debian family)"
  when: "linux_ssh_hardening_disabled is not defined or not linux_ssh_hardening_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_ssh_hardening_ubuntu"
