---

- name: "Apply login banner hardening (Ubuntu/Debian family)"
  when: "linux_login_banner_disabled is not defined or not linux_login_banner_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_login_banner_ubuntu"

...
