---

- name: "Apply Chrony NTP hardening (RHEL 9 family)"
  when: "linux_chrony_disabled is not defined or not linux_chrony_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_chrony_rhel9"

...
