---

- name: "Apply fail2ban hardening (RHEL 9 family)"
  when: "linux_fail2ban_disabled is not defined or not linux_fail2ban_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_fail2ban_rhel9"

...
