---

- name: "Apply fail2ban brute-force protection (Ubuntu/Debian family)"
  when: "linux_fail2ban_disabled is not defined or not linux_fail2ban_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_fail2ban_ubuntu"

...
