---
- name: "Restart sshd"
  ansible.builtin.service:
    name: "sshd"
    state: "restarted"

- name: "PAM changes applied"
  ansible.builtin.debug:
    msg: "Password history & expiry updated in login.defs & pwquality.conf. New sessions will apply."
