---
- name: "Converge — auditing RHEL9"
  hosts: all
  gather_facts: true
  become: true

  vars:
    # Disable remote forwarding — no syslog server in test environment
    linux_auditing_forwarding_disabled: true

  tasks:
    - name: "Include linux_auditing_rhel9"
      ansible.builtin.include_role:
        name: "linux_auditing_rhel9"
