---
- name: "Prepare — sudo_hardening RHEL9"
  hosts: rhel9
  gather_facts: false
  become: false

  tasks:
    - name: "Update dnf cache"
      ansible.builtin.raw: dnf makecache -q
      changed_when: false

- name: "Prepare — sudo_hardening Ubuntu"
  hosts: ubuntu
  gather_facts: false
  become: true

  tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
