---

- name: "Restart auditd"
  ansible.builtin.service:
    name: "auditd"
    state: "restarted"
  failed_when: false

- name: "Restart rsyslog"
  ansible.builtin.service:
    name: "rsyslog"
    state: "restarted"

...
