---

collections:
  # CyberAar hardening collection (update name when cyberaar namespace is approved)
  - name: bantou96.hardening
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.5.4"      # for firewalld, selinux, seboolean, etc.
  - name: community.general
    version: ">=8.0.0"      # sometimes useful for extra modules

...
