---

- name: "Apply IP forwarding and network hardening (Ubuntu/Debian family)"
  when: "linux_ip_forwarding_disabled is not defined or not linux_ip_forwarding_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_ip_forwarding_ubuntu"

...
