---
- name: "Apply /tmp mount hardening (Ubuntu/Debian family)"
  when: "linux_tmp_mounts_disabled is not defined or not linux_tmp_mounts_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_tmp_mounts_ubuntu"
