---

- name: "Apply AIDE file integrity monitoring (Ubuntu/Debian family)"
  when: "linux_aide_disabled is not defined or not linux_aide_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_aide_ubuntu"

...
