---

- name: "Apply auditd auditing hardening (Ubuntu/Debian family)"
  when: "linux_auditing_disabled is not defined or not linux_auditing_disabled | bool"
  ansible.builtin.import_tasks: "tasks.yml"
  tags: "linux_auditing_ubuntu"

...
